### ISSUE TITLE
expose logs around the service memory footprint

### ISSUE THREAD

**Issue by techsavvyash** [BharatSahAIyak/bhasai-auth-service#22]
## Description

The aim of this ticket is to setup tooling which allows for realtime check around the amount of memory the nest service is taking up.

**Comment by techsavvyash** [comment]
@Zolo-Ryan to send in the PR features implemented.

**Comment by Zolo-Ryan** [comment]
Here is a preview of how the memory footprint looks like
![image](https://github.com/BharatSahAIyak/bhasai-auth-service/assets/119104324/8b3ea285-a0f3-4d7e-91b4-6e5c4e8bbd08)
